name: 3d-cnn-torch
channels:
  - pytorch
  - conda-forge
  - default
  - mrcfile
dependencies:
  - python=3.6
  - jupyter
  - imageio
  - h5py
  - keras
  - pytorch=0.4.1
  - torchvision
  - scikit-learn
  - scikit-image
  - tensorboardX
  - tqdm
  - pandas
