tomos_sets:
  -2:
    test_list: ["ScED_6h/001", "ScED_6h/002", "ScED_6h/003", "ScED_6h/006", "ScED_6h/011",
                "ScED_6h/015", "ScED_6h/019", "ScED_6h/021", "ScED_6h/022", "ScED_6h/023",
                "ScED_6h/035", "ScED_6h/036", "ScED_6h/037", "ScED_6h/039", "ScED_6h/041",]
    model_name: "64pix_encoder_dropout0_decoder_dropout0_DA_none_BN_False_ribo__D_2_IF_4_set_1"
  -1:
    test_list: ["ScED_6h/044", "ScED_6h/047", "ScED_6h/049", "ScED_6h/054", "ScED_6h/055",
                "ScED_6h/056", "ScED_6h/057", "ScED_6h/058", "ScED_6h/059", "ScED_6h/062",
                "ScED_6h/064", "ScED_6h/065", "ScED_6h/069", "ScED_6h/070"]
    model_name: "64pix_encoder_dropout0_decoder_dropout0_DA_none_BN_False_ribo__D_2_IF_4_set_1"
  -3:
    test_list: ["ScED_6h/001", "ScED_6h/002", "ScED_6h/003", "ScED_6h/006", "ScED_6h/011",
                "ScED_6h/015", "ScED_6h/019", "ScED_6h/021", "ScED_6h/022", "ScED_6h/023",
                "ScED_6h/035", "ScED_6h/036", "ScED_6h/037", "ScED_6h/039", "ScED_6h/041",]
    model_name: "64pix_encoder_dropout0_decoder_dropout0_DA_none_BN_False_ribo__D_2_IF_8_set_1"
  -4:
    test_list: ["ScED_6h/044", "ScED_6h/047", "ScED_6h/049", "ScED_6h/054", "ScED_6h/055",
                "ScED_6h/056", "ScED_6h/057", "ScED_6h/058", "ScED_6h/059", "ScED_6h/062",
                "ScED_6h/064", "ScED_6h/065", "ScED_6h/069", "ScED_6h/070"]
    model_name: "64pix_encoder_dropout0_decoder_dropout0_DA_none_BN_False_ribo__D_2_IF_8_set_1"

dataset_table: "/struct/mahamid/Irene/yeast/yeast_table.csv"
overlap: 12
write_on_table: true
partition_name: "test_partition_1xf"
processing_tomo: "1xf_tomo"
box_shape: 64
output_dir: "/struct/mahamid/Irene/yeast"

unet_hyperparameters:
  models_table: "/struct/mahamid/Irene/yeast/config_models/ribo/models.csv"
  #  model_name: "64pix_encoder_dropout0_decoder_dropout0.2_DA_none_BN_False_ribo__D_2_IF_32_set_3"
  label_name: "ribo_sph_masks_TM_CNNs"

reconstruction:
  reconstruction_path: "/struct/mahamid/Irene/scratch/trueba/3d-cnn/cnn_evaluation"
  class_number: 0
  semantic_classes: ["ribo"]

motl_parameters:
  min_cluster_size: 1000
  max_cluster_size: 5000
  ignore_border_thickness: 10
  filtering_mask: "cytosol_mask" #'lamella_file'

performance_parameters:
  clean_motl: 'path_to_motl_clean_ribo'
  pr_tolerance_radius: 10
  statistics_file: null #"/struct/mahamid/Irene/yeast/config_models/ribo/statistics.csv"
