tomos_sets:
  -1:
    test_list: ["190301/004"]
#    model_name: "64pix_encoder_dropout0_decoder_dropout0_DA_none_BN_False_ribo__D_2_IF_4_set_1"
  -2:
    test_list: ["190301/007"]
#    model_name: "64pix_encoder_dropout0_decoder_dropout0_DA_none_BN_False_ribo__D_2_IF_4_set_1"
  -3:
    test_list: ["190301/014"]
#    model_name: "64pix_encoder_dropout0_decoder_dropout0_DA_none_BN_False_ribo__D_2_IF_4_set_1"
  -4:
    test_list: ["190301/017"]
#    model_name: "64pix_encoder_dropout0_decoder_dropout0_DA_none_BN_False_ribo__D_2_IF_4_set_1"
  -5:
    test_list: ["190301/018"]
#    model_name: "64pix_encoder_dropout0_decoder_dropout0_DA_none_BN_False_ribo__D_2_IF_4_set_1"
  -6:
    test_list: ["190301/019"]
#    model_name: "64pix_encoder_dropout0_decoder_dropout0_DA_none_BN_False_ribo__D_2_IF_4_set_1"
  
  -11:
    test_list: ["190301/006"]
    model_name: "64pix_encoder_dropout0_decoder_dropout0_DA_none_BN_False_ribo__D_2_IF_4_set_1"
  -12:
    test_list: ["190301/013"]
    model_name: "64pix_encoder_dropout0_decoder_dropout0_DA_none_BN_False_ribo__D_2_IF_4_set_1"
  -13:
    test_list: ["190301/020"]
    model_name: "64pix_encoder_dropout0_decoder_dropout0.2_DA_none_BN_False_ribo__D_2_IF_32_set_1"
  -14:
    test_list: ["190301/029"]
    model_name: "64pix_encoder_dropout0_decoder_dropout0_DA_none_BN_False_ribo__D_2_IF_4_set_1"
  -21:
    test_list: ["190301/002"]
    model_name: "64pix_encoder_dropout0_decoder_dropout0_DA_none_BN_False_ribo__D_2_IF_4_set_2"
  -22:
    test_list: ["190301/011"]
    model_name: "64pix_encoder_dropout0_decoder_dropout0_DA_none_BN_False_ribo__D_2_IF_4_set_2"
  -23:
    test_list: ["190301/021"]
    model_name: "64pix_encoder_dropout0_decoder_dropout0_DA_none_BN_False_ribo__D_2_IF_4_set_2"
  -24:
    test_list: ["190301/030"]
    model_name: "64pix_encoder_dropout0_decoder_dropout0_DA_none_BN_False_ribo__D_2_IF_4_set_2"
  -31:
    test_list: ["190301/001"]
    model_name: "64pix_encoder_dropout0_decoder_dropout0_DA_none_BN_False_ribo__D_2_IF_4_set_3"
  -32:
    test_list: ["190301/010"]
    model_name: "64pix_encoder_dropout0_decoder_dropout0_DA_none_BN_False_ribo__D_2_IF_4_set_3"
  -33:
    test_list: ["190301/015"]
    model_name: "64pix_encoder_dropout0_decoder_dropout0_DA_none_BN_False_ribo__D_2_IF_4_set_3"
  -34:
    test_list: ["190301/026"]
    model_name: "64pix_encoder_dropout0_decoder_dropout0_DA_none_BN_False_ribo__D_2_IF_4_set_3"

  1:
    training_list: [ "190301/001", "190301/002", "190301/004", "190301/007",
                     "190301/010", "190301/011", "190301/014", "190301/015",
                     "190301/017", "190301/018", "190301/019", "190301/021",
                     "190301/026", "190301/030",
    ]
    test_list: ["190301/006","190301/013","190301/020","190301/029"]
    model_name: "64pix_encoder_dropout0_decoder_dropout0_DA_none_BN_False_ribo__D_2_IF_4_set_1"

  2:
    training_list: [ "190301/001", "190301/004", "190301/006", "190301/007",
                     "190301/010", "190301/013", "190301/014", "190301/015",
                     "190301/017", "190301/018", "190301/019", "190301/020",
                     "190301/026", "190301/029",
    ]
    test_list: ["190301/002","190301/011","190301/021","190301/030"]
    model_name: "64pix_encoder_dropout0_decoder_dropout0_DA_none_BN_False_ribo__D_2_IF_4_set_2"

  3:
    training_list: [ "190301/002", "190301/004", "190301/006", "190301/007",
                     "190301/011", "190301/013", "190301/014", "190301/017",
                     "190301/018", "190301/019", "190301/020", "190301/021",
                     "190301/029", "190301/030",
    ]
    test_list: ["190301/001","190301/010","190301/015","190301/026"]
    model_name: "64pix_encoder_dropout0_decoder_dropout0_DA_none_BN_False_ribo__D_2_IF_4_set_3"

dataset_table : "/struct/mahamid/Irene/yeast/yeast_table.csv"
overlap : 12
write_on_table : True
partition_name : "test_partition_1xf"
processing_tomo : "1xf_tomo"
box_shape : 64
output_dir: "/struct/mahamid/Irene/yeast/ED"

unet_hyperparameters:
  models_table: "/struct/mahamid/Irene/yeast/config_models/ribo/models.csv"
  model_name: "64pix_encoder_dropout0_decoder_dropout0.2_DA_none_BN_False_ribo__D_2_IF_32_set_3"
  label_name : "ribo_sph_masks_TM_CNNs"

reconstruction:
  reconstruction_path : "/struct/mahamid/Irene/scratch/trueba/3d-cnn/cnn_evaluation"
  class_number : 0
  semantic_classes: ["ribo"]

motl_parameters:
  min_cluster_size: 100
  max_cluster_size: 35000
  ignore_border_thickness : 10
  filtering_mask : 'lamella_file'

performance_parameters:
  clean_motl : 'path_to_motl_clean_ribo'
  pr_tolerance_radius : 10
  statistics_file : "/struct/mahamid/Irene/yeast/config_models/ribo/statistics.csv"
